version: '3'
services:
  app:
    container_name: imgur
    restart: always
    build: .
    environment: 
      - APP_PORT=5050
    ports:
      - 5000:5050
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - ./mongodb:/data/db
